/**
 * Single source of truth for colours, light + dark.
 * `node scripts/palette.mjs` regenerates src/app/theme.css (CSS variables).
 * tailwind.config.ts maps every token to `rgb(var(--<name>) / <alpha-value>)`.
 *
 * Rules: brand fills (400–700) are identical in both themes (Duolingo keeps its
 * colours in dark mode); tints (50–200) become dark tinted surfaces; text
 * shades (800) become light so text stays ≥ 4.5:1 on the dark background.
 */
import { writeFileSync } from "node:fs";

export const palette = {
  // name: { shade: [light, dark] }
  surface: { DEFAULT: ["#FFFFFF", "#131F24"], raised: ["#FFFFFF", "#202F36"] },
  ink: {
    50: ["#F7F7F7", "#1B2A31"], 100: ["#F0F0F0", "#22333B"], 200: ["#E5E5E5", "#37464F"],
    300: ["#CECECE", "#52656D"], 400: ["#AFAFAF", "#6F838D"], 500: ["#6B6B6B", "#9DB0BA"],
    700: ["#4B4B4B", "#DCE6EC"], 900: ["#3C3C3C", "#F1F7FB"],
  },
  leaf: {
    50: ["#F1FFE6", "#1C2F17"], 100: ["#D7FFB8", "#22381A"], 200: ["#A5ED6E", "#3B6526"],
    400: ["#79D634", "#79D634"], 500: ["#58CC02", "#58CC02"], 600: ["#58A700", "#58A700"],
    700: ["#4A8F00", "#4A8F00"], 800: ["#3B7300", "#93D333"],
  },
  ocean: {
    50: ["#DDF4FF", "#11303F"], 100: ["#BCE9FF", "#163E52"], 400: ["#49C0F8", "#49C0F8"],
    500: ["#1CB0F6", "#1CB0F6"], 600: ["#1899D6", "#1899D6"], 700: ["#1482B8", "#1482B8"], 800: ["#0C6694", "#5CC8FA"],
  },
  sun: {
    50: ["#FFF8DB", "#33290C"], 100: ["#FFF0B3", "#41340D"], 400: ["#FFD43B", "#FFD43B"],
    500: ["#FFC800", "#FFC800"], 600: ["#E5A800", "#E5A800"], 800: ["#855C00", "#FFD43B"],
  },
  coral: {
    50: ["#FFF0F0", "#3A1D21"], 100: ["#FFDFE0", "#46222A"], 400: ["#FF7878", "#FF7878"],
    500: ["#FF4B4B", "#FF4B4B"], 600: ["#EA2B2B", "#EA2B2B"], 700: ["#C81F1F", "#C81F1F"], 800: ["#A51717", "#FF8F8F"],
  },
  gem: { 50: ["#E8FAFD", "#0F2F36"], 400: ["#4FD1E8", "#4FD1E8"], 500: ["#1CB8D9", "#1CB8D9"], 600: ["#1393AE", "#1393AE"], 800: ["#0B6577", "#5ED8EE"] },
  flame: { 50: ["#FFF3E0", "#36250D"], 400: ["#FFB020", "#FFB020"], 500: ["#FF9600", "#FF9600"], 600: ["#E07F00", "#E07F00"], 800: ["#9A4F00", "#FFB547"] },
  grape: { 50: ["#F7EEFF", "#2C2140"], 400: ["#DCA8FF", "#DCA8FF"], 500: ["#CE82FF", "#CE82FF"], 600: ["#A568CC", "#A568CC"], 800: ["#7339A0", "#DDAEFF"] },
};

const rgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16)).join(" ");
const varName = (color, shade) => (shade === "DEFAULT" ? `--${color}` : `--${color}-${shade}`);

export function cssVariables() {
  const block = (i) =>
    Object.entries(palette)
      .flatMap(([color, shades]) => Object.entries(shades).map(([shade, pair]) => `  ${varName(color, shade)}: ${rgb(pair[i])};`))
      .join("\n");
  return `/* GENERATED by scripts/palette.mjs. Edit the palette there, then: node scripts/palette.mjs */
:root {
  color-scheme: light;
${block(0)}
}

.dark {
  color-scheme: dark;
${block(1)}
}
`;
}

// Run directly (`node scripts/palette.mjs`) to regenerate the CSS.
if (process.argv[1]?.endsWith("palette.mjs")) {
  writeFileSync(new URL("../src/app/theme.css", import.meta.url), cssVariables());
  console.log("wrote src/app/theme.css");
}
